import { getRandomDate } from "@/lib/utils";

import { IAllFormsSection } from "./AllFormsSection";

const base: IAllFormsSection = {
  data: [
    {
      id: 1,
      name: "volunteer signup",
      description: "Join our volunteer program.",
      createdAt: getRandomDate(90),
      visits: 5,
      published: true,
    },
    {
      id: 1,
      name: "beta tester form",
      description: "",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "support request",
      description: "Request support from the team.",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "contact form",
      description: "Used to get in touch.",
      createdAt: getRandomDate(90),
      visits: 7,
      published: true,
    },
    {
      id: 1,
      name: "job application",
      description: "Apply for open roles.",
      createdAt: getRandomDate(90),
      visits: 9,
      published: true,
    },
    {
      id: 1,
      name: "internal review form",
      description: "",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "feedback form",
      description: "",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "newsletter signup",
      description: "Subscribe for upcreatedAts.",
      createdAt: getRandomDate(90),
      visits: 3,
      published: true,
    },
  ],
  loading: false,
  error: false,
};

const oneRow: IAllFormsSection = {
  data: [
    {
      id: 1,
      name: "registration form",
      description: "For event signups.",
      createdAt: getRandomDate(90),
      visits: 7,
      published: true,
    },
    {
      id: 1,
      name: "feedback form",
      description: "",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "survey form",
      description: "A quick survey.",
      createdAt: getRandomDate(90),
      visits: 11,
      published: true,
    },
    {
      id: 1,
      name: "job application",
      description: "Used to apply for jobs.",
      createdAt: getRandomDate(90),
      visits: 5,
      published: true,
    },
  ],
  loading: false,
  error: false,
};

const threeRows: IAllFormsSection = {
  data: [
    {
      id: 1,
      name: "feedback form",
      description: "Collects user feedback.",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "employment form",
      description: "Used for job applications.",
      createdAt: getRandomDate(90),
      visits: 3,
      published: true,
    },
    {
      id: 1,
      name: "survey form",
      description: "General opinion survey.",
      createdAt: getRandomDate(90),
      visits: 15,
      published: true,
    },
    {
      id: 1,
      name: "registration form",
      description: "Event registration.",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "feedback form",
      description: "",
      createdAt: getRandomDate(90),
      visits: 8,
      published: true,
    },
    {
      id: 1,
      name: "newsletter signup",
      description: "Sign up for upcreatedAts.",
      createdAt: getRandomDate(90),
      visits: 2,
      published: true,
    },
    {
      id: 1,
      name: "bug report",
      description: "",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "survey form",
      description: "Quick survey.",
      createdAt: getRandomDate(90),
      visits: 6,
      published: true,
    },
    {
      id: 1,
      name: "contact form",
      description: "Reach out to us.",
      createdAt: getRandomDate(90),
      visits: 4,
      published: true,
    },
    {
      id: 1,
      name: "feedback form",
      description: "",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "volunteer form",
      description: "Join as a volunteer.",
      createdAt: getRandomDate(90),
      visits: 1,
      published: true,
    },
    {
      id: 1,
      name: "application form",
      description: "For internal use.",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
  ],

  loading: false,
  error: false,
};

const loading: IAllFormsSection = {
  data: [
    {
      id: 1,
      name: "volunteer signup",
      description: "Join our volunteer program.",
      createdAt: getRandomDate(90),
      visits: 5,
      published: true,
    },
    {
      id: 1,
      name: "beta tester form",
      description: "",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "support request",
      description: "Request support from the team.",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "contact form",
      description: "Used to get in touch.",
      createdAt: getRandomDate(90),
      visits: 7,
      published: true,
    },
    {
      id: 1,
      name: "job application",
      description: "Apply for open roles.",
      createdAt: getRandomDate(90),
      visits: 9,
      published: true,
    },
    {
      id: 1,
      name: "internal review form",
      description: "",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "feedback form",
      description: "",
      createdAt: getRandomDate(90),
      visits: 0,
      published: false,
    },
    {
      id: 1,
      name: "newsletter signup",
      description: "Subscribe for upcreatedAts.",
      createdAt: getRandomDate(90),
      visits: 3,
      published: true,
    },
  ],
  loading: true,
  error: false,
};

const noData: IAllFormsSection = {
  data: [],
  loading: false,
  error: false,
};

export const mockAllFormsSectionProps = {
  base,
  oneRow,
  threeRows,
  loading,
  noData,
};
